### ISSUE TITLE
Coordinate Systems

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/learn-gfx-hal#12]
Approximate stages

* [x] Suggest some Vector/Matrix math places because I'm no math teacher.
* [x] Introduce [nalgebra-glm](https://www.nalgebra.org/nalgebra_glm/)
* [x] Explain the different Coordinate Spaces
* [x] Model space
* [x] World space
* [x] View space
* [x] Explain Orthographic and Perspective projections.
* [x] Setup the vertex shader for the matrix math.
* [x] Index draw one cube
* [x] ~~Instanced draw 10 different cubes~~ We just use repeated draw calls, it's long enough as it is.
* [x] Make the cubes spin in place using the time

**Comment by Lokathor** [comment]
http://anki3d.org/vulkan-coordinate-system/

**Comment by icefoxen** [comment]
*hoo boy*, this is a nontrivial tutorial on it's own. I suggest finding a *really* good tutorial on this that already exists, linking to that, and translating the relevant bits to Rust.

**Comment by Lokathor** [comment]
:ferrisSweat:

I've never thought they were too complex myself. Sometimes I'm accidentally good at things though.

**Comment by jmitchell89** [comment]
Coords have been explained over and over. I would instead explain how gfx-hal differs from OGL, and explain the code in your demo/tutorial.

**Comment by Lokathor** [comment]
Well, if you're a graphics pro then it seems normal, but I'm trying to target the zero-experience crowd too, so we have to go over the concept at least some.

But yes, dimensional direction is key.

**Comment by StarArawn** [comment]
Coords have been explained over and over. I would instead explain how gfx-hal differs from OGL, and explain the code in your demo/tutorial.

**Comment by Lokathor** [comment]
PR is up. Closing the issue to divert further discussion there.

https://github.com/Lokathor/learn-gfx-hal/pull/34
