### ISSUE TITLE
05_shaders edits

### ISSUE THREAD

**Issue by icefoxen** [Lokathor/learn-gfx-hal#32]
* [x] "it's actually quite good at the jobs" -> it's actually quite good at its job
 * [x] "Ahe crate itself doesn't know how to do any compilation at all." -> The crate ...
 * [x] "Seriously you should read that book stuff and blog stuff and anything else you can about GLSL if you really want to know it all." might want an addendum saying something like "But for the simple stuff it's pretty straightforward".  Though maybe if someone's gotten that far in the tutorial they're not going to be scared off by a programming language.
 * [x] "That's because usually you'd have a single model (an "iconic triangle") and then you'd tell the shader what animation frame, or position, or global light level, or whatever else without touching the model data directly." feels like it should have a sentence after it like "the shader then computes all the changes to the model each frame on the fly".  That's a nitpick though.
 * [x] "We first add an Instant to our HalState."  add "...to record the time that the context was created" or something like that maybe?  It's basically obvious what this is for, but it might not be obvious to a newbie.
 * [x] "we'll be using uniform, buffers for Textures during the next lesson" remove comma

**Comment by Lokathor** [comment]
https://github.com/Lokathor/learn-gfx-hal/pull/33
