### ISSUE TITLE
Clear The Screen refuses to run due to dependency on shaderc

### ISSUE THREAD

**Issue by moxian** [Lokathor/learn-gfx-hal#60]
I haven't done any shader work yet, so my environment is probably not ideal, but right now trying to run

```
 cargo run --example clear_the_screen --features vulkan
```

fails at the point of trying to compile shaders. This is probably undesirable, since the first, easiest lesson should not depend on advanced environment setup.

(Why exactly it's failing, I'm not sure, but it being a C++ lib, the failure is not that surprising. I'm probably missing some libraries or some such. Or it simply blindly expects POSIX-compliance)

**Comment by Lokathor** [comment]
https://github.com/Lokathor/learn-gfx-hal/blob/master/README.md#requirements

I try to explain clearly ahead of time that you'll need to do this. Unfortunately, as soon as the second lesson kicks in you'll need `shaderc-rs` so there's not a whole lot to be gained by trying to adjust a single example to not depend on that crate.

Basically, yes, the crate assumes you have msys2 available.
