### ISSUE TITLE
Next Lesson: Proper swapchain resizing + Cleanup

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/learn-gfx-hal#67]
STOP BEING DUMB AND MAKE IT WORK THE RIGHT WAY.

Also break down the parts used so far and possibly make more "Bundle" types that pack up related things so that it's easier to see what's related at a high level.

**Comment by Lokathor** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=677488d25521857dd219b9d2dd1a99b4

**Comment by fredlangva** [comment]
Rendy will be throwing a bit of a wrench in the gears. I have been trying to get it working using your lessons here and ran into a few issues with the Rendy API (since it was changed with 0.1.1) not matching their examples. I hit a bit of a snag with instanciating the surface. Let me know if you want the code

**Comment by Lokathor** [comment]
I really don't get how examples fail to be updated in so many crates :/

But yeah, @termhn is pointing me at stuff to go by too. The biggest factor is that ive been spending time on other things the past few days (wide string support for winapi)

**Comment by termhn** [comment]
@fredlangva this isn't really the place to discuss but if there are any places where rendy examples are not working for you please file an issue on the rendy repo and/or ping me or Viral on discord--they should be updated (work for me, at least).

There are breaking changes on both `gfx-hal` master and `rendy` master that have not been pushed to crates.io yet, so the examples on the master branches will not be directly compatible with the currently released version of crates.io currently.

**Comment by fredlangva** [comment]
I got the initialization working and am slogging through the pipeline. It looks like it will be a lot less code than gfx-hal. I'm not upset about the examples being a bit out of date... it's a good learning experience for me since I am moving to Rust from 30 years on C

**Comment by termhn** [comment]
👍 I think if anything the examples are *too* up to date :P I made an issue to make sure we tag releases so that it's easy to find the proper versions of examples for released versions.

**Comment by Lokathor** [comment]
https://github.com/gfx-rs/gfx/pull/2640

**Comment by Lokathor** [comment]
This is very old, either the lesson will be explained properly in learn-rendy some day or we've already done it.

either way, we can open a new issue if people are still having problems later, so i'm cleaning this out for now.
