### ISSUE TITLE
Respect SurfaceCapabilities image_count.start

### ISSUE THREAD

**Issue by krsnik02** [Lokathor/learn-gfx-hal#83]
When creating a swaphain, it is an error if the `image_count` argument to SwapchainConfig  is smaller than `caps.image_count.start`. The current code assumes that `caps.image_count.start <= 2` which is not always true (it is 4 on my system).

This can be easily fixed by changing
```rust
let image_count = if present_mode == PresentMode::Mailbox {
    (caps.image_count.end - 1).min(3)
} else {
    (caps.image_count.end - 1).min(2)
}
````
to
````rust
let image_count = if present_mode == PresentMode::Mailbox {
    (caps.image_count.end - 1).min(caps.image_count.start.max(3))
} else {
    (caps.image_count.end - 1).min(caps.image_count.start.max(2))
}
````

**Comment by Lokathor** [comment]
This sounds good.

I'd appreciate if you could do the PR here and make sure that the change is reflected across the various example files and mentioned in the appropriate tutorial.
